"""initial migration

Revision ID: be02ba545c36
Revises: 
Create Date: 2026-04-10 11:31:59.193969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be02ba545c36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_types', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('character_types', 'type_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.drop_index(op.f('type_name'), table_name='character_types')
    op.add_column('enemies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('enemies', 'enemy_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.add_column('level_enemy_map', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'level_enemy_map', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'level_enemy_map', 'enemies', ['enemy_id'], ['id'])
    op.add_column('levels', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('levels', 'level_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('player_characters', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('player_characters', 'rarity',
               existing_type=mysql.ENUM('normal', 'advanced', 'rare', 'legendary'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               nullable=False,
               existing_server_default=sa.text("'normal'"))
    op.alter_column('player_characters', 'attack_bonus',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'defense_bonus',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'recovery_bonus',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'hp_bonus',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'operation_time_bonus',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'status',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('player_characters', 'dismissed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('skill_character_map', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('skill_character_map', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('skill_character_map', 'character_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'skill_character_map', 'skills', ['skill_id'], ['id'])
    op.add_column('skills', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('skills', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('skills', 'effect_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.add_column('team_character_map', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('team_character_map', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('team_character_map', 'character_id',
               existing_type=mysql.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.create_foreign_key(None, 'team_character_map', 'skills', ['passive_skill_id'], ['id'])
    op.create_foreign_key(None, 'team_character_map', 'skills', ['active_skill_id'], ['id'])
    op.alter_column('teams', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('teams', 'team_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('user_level_progress', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('unique_user_level'), table_name='user_level_progress')
    op.create_foreign_key(None, 'user_level_progress', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'user_level_progress', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('users', 'max_characters',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'50'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'max_characters',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'50'"))
    op.alter_column('users', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'user_level_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_level_progress', type_='foreignkey')
    op.create_index(op.f('unique_user_level'), 'user_level_progress', ['user_id', 'level_id'], unique=True)
    op.alter_column('user_level_progress', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('teams', 'team_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('teams', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'team_character_map', type_='foreignkey')
    op.drop_constraint(None, 'team_character_map', type_='foreignkey')
    op.alter_column('team_character_map', 'character_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.INTEGER(),
               nullable=False)
    op.drop_column('team_character_map', 'created_at')
    op.drop_column('team_character_map', 'id')
    op.alter_column('skills', 'effect_value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('skills', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('skills', 'created_at')
    op.drop_constraint(None, 'skill_character_map', type_='foreignkey')
    op.alter_column('skill_character_map', 'character_type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('skill_character_map', 'created_at')
    op.drop_column('skill_character_map', 'id')
    op.alter_column('player_characters', 'dismissed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('player_characters', 'status',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('player_characters', 'operation_time_bonus',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'hp_bonus',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'recovery_bonus',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'defense_bonus',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'attack_bonus',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('player_characters', 'rarity',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=mysql.ENUM('normal', 'advanced', 'rare', 'legendary'),
               nullable=True,
               existing_server_default=sa.text("'normal'"))
    op.alter_column('player_characters', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('levels', 'level_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('levels', 'created_at')
    op.drop_constraint(None, 'level_enemy_map', type_='foreignkey')
    op.drop_constraint(None, 'level_enemy_map', type_='foreignkey')
    op.drop_column('level_enemy_map', 'id')
    op.alter_column('enemies', 'enemy_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('enemies', 'created_at')
    op.create_index(op.f('type_name'), 'character_types', ['type_name'], unique=True)
    op.alter_column('character_types', 'type_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('character_types', 'created_at')
    # ### end Alembic commands ###
